/* Host-side generator for the pre-rendered gauge face.
 *
 * The face is static, so it lives in flash (LTDC fetches layer 1
 * straight from there), freeing all of AXI SRAM for the needle sprite
 * ping-pong buffers. Rerun this whenever the face art in gauge.c
 * changes:
 *
 *   cc tools/genface.c Display/gauge.c -IDisplay -lm -o /tmp/genface \
 *     && /tmp/genface > Display/face_img.c
 */
#include <stdio.h>
#include "gauge.h"

static unsigned char fb[720 * 720];

int main(void) {
    Gauge_RenderFace(fb, 720, 720);
    printf("/* Generated by tools/genface.c — do not edit. */\n");
    printf("#include <stdint.h>\n\n");
    printf("__attribute__((aligned(64)))\n");
    printf("const uint8_t Gauge_FaceImg[720 * 720] = {\n");
    for (int i = 0; i < 720 * 720; i++)
        printf("%d,%s", fb[i], (i % 32 == 31) ? "\n" : "");
    printf("};\n");
    return 0;
}
